spring.application.name=MPOS-INTEGRATION
server.port=8897

logging.level.ROOT= INFO
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
management.endpoint.health.enabled=true
java.awt.headless=true
app.pos.version=1.0.1
app.pos.date=30-01-2026
#spring.thymeleaf.prefix=D:\\addlnUtils\\mf-pos-impl\\morefun-pos-implementation\\src\\main\\resources\\templates\\
spring.thymeleaf.prefix=classpath:/templates/
server.error.whitelabel.enabled=false
server.servlet.context-path=/mp63
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=11MB
spring.servlet.multipart.enabled=true
#spring.mvc.static-path-pattern=/resources/static/**
